use_frameworks!

platform :ios, '14.0'

target 'BeaconIpmagix_Example' do
  pod 'BeaconIpmagix', :path => '../'
  pod 'IQKeyboardManagerSwift'

  target 'BeaconIpmagix_Tests' do
    inherit! :search_paths
    
  end
end
